# Generated by Django 5.1.3 on 2024-12-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_alter_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
